project:
  type: website
  output-dir: /

website:
  title: "aniketadhikari.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aniketadhikari
      - icon: linkedin
        href: https://linkedin.com/in/aniket-adhikari
format:
  html:
    theme: morph
    css: styles.css



