project:
  type: website
  output-dir: /

website:
  title: "CS 5805 Machine Learning Blog"
  navbar:
    style: docked
    background: primary 
    search: true
    page-footer: "Copyright 2023, Aniket Adhikari" 
    reader-mode: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aniketadhikari
      - icon: linkedin
        href: https://linkedin.com/in/aniket-adhikari
format:
  html:
    theme: lux
    css: styles.css
  



