project:
  type: website
  output-dir: /

website:
  title: "Aniket Adhikari Portfolio"
  search:
    location: navbar
    type: overlay
  navbar:
    style: docked
    background: primary 
    search: true
    reader-mode: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aniketadhikari
      - icon: linkedin
        href: https://linkedin.com/in/aniket-adhikari
format:
  html:
    theme: lux
    css: styles.css
  



