---
title: "Probability Theory"
author: "Aniket Adhikari"
date: "2023-10-23"
date-modified: "2023-11-13"
---
---
# What is Probability Theory?
The outcome of random events like rolling a pair of dice are impossible to predict with absolute certainty. Probability theory provides a mathematical framework for quantifying uncertainty and randomness in these situations where outcome is not deterministic. 

Under the umbrella of probability theory is a couple of key concepts that I will be going through, such as:

-   Random Variables
-   Independence
-   Conditional Probability
-   Bayes Theorem

# Areas of Importance

Probability theory has proven to be crucial in various fields including, but not limited to: 

1. Economics

In economics, probability models are used to forecast certain economic indicators like annual GDP growth, inflation, and unemployment rates. Through these forecasts, policymakers are able to make informed decisions about the macroeconomy [2]

2. Finance 

Probability theory is fundamental for assessing risk in financial markets. It has a massive influence on how institutional and individual investors make decisions regarding buying and selling of securities. It also influences the way financial derivatives like options are priced by sellers [2].

3. Medicine

3 years ago, the whole world was shut down by COVID-19, which resulted in many people falling ill. In instances like this, epidemiologists utilize predictive algorithms to measure the probability of patients being carriers disease carriers based on symptom screening. By identifying novel cases of COVID-19, there is potential that it can be identified early, which can help to reduce long-term complications and even save lives [3]

# Random Variables 
In the context of probability theory, a random variable is usually designated as $X$ and can take on different numerical values a as result of random events/experiments. The numerical values associated with the outcome of the event are determined by the underlying probability space[4].[5]. There are 2 types of random variables values: 

## Discrete Variable
**Discrete variables** are variables that can only take on certain discrete, countable values. It is restricted to integers and can not be represented as a decimal or fraction. 

Examples:
- Counts and integers like number of items or scores
- Binary variables like pass/fail or yes/no 
- Rating scales like rating movies on a 1-5 star scale
- Event outcomes such as a dice roll or coin flip

## Continuous Variables
**Continuous variables** are able to take on an infinite number of real values within a range. It can take on fractional or decimal values in addition to integer values.

Examples: 
* Physical measurements like height, weight, temperature
* Time, geographic coordinates
* Natural phenomena like air pressure 

#  Independence
In probability theory, we say that two events $A$ and $B$ are independent if the occurence of one of the events does not effect the probability of the other event. That is, $P(A|B)=P(A)$ and $P(B|A)=P(B)$. 

For independent events, the probability of both occuring is the product of their respective probabilities. That is, $P(A \cap B)=P(A)*P(B)$

Independence can be used to determine whether the probability of one event is dependent on the outcome of another or not. Events that are not independent are dependent, meaning the occurence of one event influences the outcome of another. In statists, we want samples to be independent so we don't introduce bias.

An example of independence would be a coin flip.  If we were to flip 2 coins, the outcome of one of the coins is not going to effect the other since they are independent. Another example would be rolling a pair of dice. The outcome of one dice does not affect another pair.

# Conditional Probability
Conditional probability refers to the measure of probability of an event $A$ occuring, given an another event $B$ has already occured. That us, $P(A|B)$. 

An example of conditional probability would be the probability that someone has the flu, given they are coughing. 

# Bayes' Theorem
Bayes' Theorem is a formula that is used to calculate conditional probabilities. Essentially, it describes the probability of an event $A$, given that there is some new information $B$. That is, $P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}$. 

Bayes' Theorem is really useful in Machine Learning and statistics since it is used to update probability distributions based on observed data. 