---
title: "Anomaly/Outlier Detection"
subtitle: "Using Python to Detect Anomalies/Outliers"
author: "Aniket Adhikari"
date: "2023-11-23"
date-modified: "2023-11-23"
toc: true
toc-title: "On this page"
code-line-numbers: true
highlight-style: dracula
format:
  html:
    embed-resources: true
    code-tools: true
  pdf:
    colorlinks: true
---

Anomaly detection, or outlier detection, is a machine learning process of detecting abnormal or rare observations in data that stick out from the rest of the data. Typically, outliers are data points that appear far away from other observations, meaning they differ greatly from the majority of the data

# Importance of Anomalies 

1. Improves Model Accuracy

Outliers can adversely effect model predictions if they aren't handled. Models might overfit to outliers and lead to reduced generalization on unseen data. Removing outliers can help to improve model accuracy and prevent misleading models. 

2. Reduce Risks of Bad Decisions 

Outlier driven misleading models can result in incorrect data interpretations and decisions. Furthermore, outliers can influence decision-making processes in various domains, from finance to healthcare. Properly handling outliers ensures that decisions are based on accurate and representative information.

3. Identify Cost-saving Opportunities

Analyzing positive outliers can reveal best practices and improvement opportunities leading to greater efficiencies. Likewise, negative outliers may show problems needing addressing.

# Anomaly/Outlier Detection in Practice?

**Fraud Detection in Finance** $\rightarrow$ Identifying transactions, claims, or activity that is suspicious and does not conform to regular patterns

* Track credit card fraud 
* Detect money laundering
* Detect unusual trading patterns in stock markets 

**Health Care** $\rightarrow$ Monitoring patient data for anomalies

* Disease detection based on electrocardiogram (ECG) readings
* Uncover irregularities in medical imaging for cancer detection 

**Cybersecurity** $\rightarrow$ Detecting unsual activity or malicious traffic on computer networks

* Detect network intrusion
* Prevent data exfiltration attempts 
* Enhance cybersecurity measures

**Manufacturing and Quality Control** $\rightarrow$ Finding defects in manufacturing

* Prevention of defective products from reaching consumers
* Reduce waste 
* Maintain product quality

**Energy and Utilities Consumption** $\rightarrow$ Finding anomalies in energy consumption patterns 

* Identify power grid failures 
* Identify abnormal usage
* Determine equipment malfunctions
* Ensure reliable service delivery 

# Types of Outliers 

## Visualization 

* Use of scatter plots, box plots, histogram distributions 